version: '3.7'

services:
  elasticsearch:
    build: ./elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elk

  logstash:
    build: ./logstash
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./cowrie/logs:/var/log/cowrie
    depends_on:
      - elasticsearch
    networks:
      - elk

  kibana:
    build: ./kibana
    container_name: kibana
    ports:
      - "127.0.0.1:5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk

  cowrie:
    image: cowrie/cowrie:latest
    container_name: cowrie
    volumes:
      - ./cowrie/cowrie.cfg:/etc/cowrie/cowrie.cfg
      - ./cowrie/logs:/var/log/cowrie
    ports:
      - "22:2222"
    networks:
      - elk

volumes:
  esdata:

networks:
  elk:
    driver: bridge
