version: '3'
services:
  cowrie:
    build: ./cowrie
    ports:
      - "2222:2222"  # Cowrie SSH
      - "2223:2223"  # Cowrie Telnet
    volumes:
      - ./cowrie/logs:/cowrie/log
      
  elk:
    image: sebp/elk
    ports:
      - "5601:5601"  # Kibana
      - "9200:9200"  # Elasticsearch
      - "5044:5044"  # Logstash
    volumes:
      - ./elk/logs:/var/log/elasticsearch
      - ./elk/logstash.conf:/etc/logstash/conf.d/logstash.conf

networks:
  default:
    driver: bridge


